//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzegladBazy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupy_raportowe
    {
        public int idGrupy { get; set; }
        public string nazwaGrupy { get; set; }
        public int numerGrupy { get; set; }
        public Nullable<bool> czy_analogowo_cyfrowa { get; set; }
    }
}
