//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzegladBazy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class komunikaty
    {
        public int id { get; set; }
        public long data_utworzenia { get; set; }
        public string tresc { get; set; }
        public int zmiana { get; set; }
        public string data_waznosci { get; set; }
    }
}
