//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzegladBazy.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class multicont
    {
        public int idOdczytu { get; set; }
        public string nazwa { get; set; }
        public double wartosc { get; set; }
        public string jednostka { get; set; }
        public int gateId { get; set; }
        public string czas { get; set; }
    }
}
