//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzegladBazy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pomiary_reczne_v
    {
        public int idPomiaru { get; set; }
        public int gateId { get; set; }
        public double value { get; set; }
        public Nullable<System.DateTime> czas_pomiaru { get; set; }
        public long time { get; set; }
        public string description { get; set; }
        public int idUzytkownika { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> data_wprowadzenia_pomiaru { get; set; }
        public long data_wprowadzenia { get; set; }
        public string nazwa { get; set; }
        public string miejsce { get; set; }
        public string uwagi { get; set; }
    }
}
