//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzegladBazy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pomiary
    {
        public int idPomiaru { get; set; }
        public int gateId { get; set; }
        public double value { get; set; }
        public long time { get; set; }
        public int idUzytkownika { get; set; }
        public long data_wprowadzenia { get; set; }
        public int id_rodzaju_pomiaru { get; set; }
        public Nullable<int> miejsce { get; set; }
        public string uwaga { get; set; }
        public bool czy_sprzedaz { get; set; }
        public string planowana_data { get; set; }
        public Nullable<int> id_zlecenia_wywozowego { get; set; }
        public Nullable<int> id_zlecenia_przywozowego { get; set; }
    
        public virtual miejsca_pomiaru miejsca_pomiaru { get; set; }
        public virtual rodzaje_pomiarow rodzaje_pomiarow { get; set; }
        public virtual rodzaje_pomiarow rodzaje_pomiarow1 { get; set; }
        public virtual rodzaje_pomiarow rodzaje_pomiarow2 { get; set; }
        public virtual uzytkownicy uzytkownicy { get; set; }
        public virtual uzytkownicy uzytkownicy1 { get; set; }
        public virtual uzytkownicy uzytkownicy2 { get; set; }
    }
}
