//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzegladBazy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class potwierdzone_komunikaty
    {
        public int id_pracownik { get; set; }
        public int id_komunikatu { get; set; }
    }
}
