//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzegladBazy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class slownik_bramek_zewnetrznych
    {
        public int id { get; set; }
        public string opis { get; set; }
        public bool aktywna { get; set; }
        public bool stworzono_zdarzenie { get; set; }
    }
}
