//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzegladBazy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_elementy_grup
    {
        public int idGrupy { get; set; }
        public string nazwa { get; set; }
        public int gateId { get; set; }
        public string description { get; set; }
    }
}
