//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrzegladBazy.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class zmiany
    {
        public int id_zmiany { get; set; }
        public int godzina_poczatku { get; set; }
    }
}
